services:
  # Backend API service
  - type: web
    name: danknet-api
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
    
  # Frontend static site
  - type: web
    name: danknet-frontend
    env: node
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npx serve -s frontend/build
    envVars:
      - key: NODE_VERSION
        value: 16.13.0
