services:
  # Backend API service
  - type: web
    name: danknet-api
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
    
  # Frontend static site
  - type: static
    name: danknet-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
